addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.2")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.5")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.11")
addSbtPlugin("com.github.scalaprops" % "sbt-scalaprops" % "0.3.1")
addSbtPlugin("org.tpolecat" % "tut-plugin" % "0.6.12")
